#!/usr/bin/env python

import sys
import os
import re

CHANGE_INFO = '[CHANGE THIS TO YOUR INFORMATION]'
HEADER_COMMENT_TEXT = """\/\*\*
 \* CS 140 Object-Oriented Programming Using C\+\+
 \* CRN: (.*)
 \* Assignment: HelloWorld
 \*
 \* Statement of code ownership: I hereby state that I have written all of this
 \* code and I have not copied this code from any other person or source\.
 \*
 \* @author (.*)
 \*\/"""

def checkForHeaderComment(fileName):
	f = open(fileName, 'r')
	matcher = re.compile(HEADER_COMMENT_TEXT)
	matches = matcher.findall(f.read())
	if len(matches) <= 0:
		if not re.match('.*_unittest\.(h|cc|cpp|c)$', fileName):
			print("WARNING: The file " +  fileName + " does not contain\nproper header comment. See http://209.129.49.15/")
		return

	for match in matches.pop():
		if match == CHANGE_INFO:
			print('WARNING: Don\'t forget to change ' + CHANGE_INFO + '\nin ' + fileName + ' to your info (or anything else)\n')
			return


lines = os.popen("git diff --cached --name-status").read().strip().split("\n")
for line in lines:
	if len(line) <= 0:
		continue
	[status, file] = re.split('\s+', line)
	if (status == 'A' or status == 'M') and (re.match('.*\.(h|cc|cpp|c)$', file)):
		checkForHeaderComment(file)
