#!/usr/bin/env python

import sys
import os
import re

lines = os.popen("git diff --cached --name-status").read().strip().split("\n")
for line in lines:
	[status, file] = re.split('\s+', line)
	print("Status: " + status + " File: " + file)